import type { ThemeTokens } from './tokens';

/**
 * Theme source type
 */
export type ThemeSource = 'builtin' | 'user' | 'ai';

/**
 * Theme metadata
 */
export interface ThemeMeta {
  /** Version of the theme schema */
  version: string;
  /** Creation timestamp */
  createdAt: number;
  /** Last updated timestamp */
  updatedAt?: number;
  /** Source of the theme */
  source: ThemeSource;
  /** Original AI prompt if generated by AI */
  aiPrompt?: string;
  /** AI model used for generation */
  aiModel?: string;
}

/**
 * Theme definition
 */
export interface Theme {
  /** Unique identifier */
  id: string;
  /** Display name */
  name: string;
  /** Optional description */
  description?: string;
  /** Theme tokens */
  tokens: ThemeTokens;
  /** Theme metadata */
  meta: ThemeMeta;
}

/**
 * Theme creation input (without auto-generated fields)
 */
export interface ThemeInput {
  id: string;
  name: string;
  description?: string;
  tokens: ThemeTokens;
  source?: ThemeSource;
}

/**
 * Create a theme from input
 */
export function createTheme(input: ThemeInput): Theme {
  return {
    id: input.id,
    name: input.name,
    description: input.description,
    tokens: input.tokens,
    meta: {
      version: '1.0.0',
      createdAt: Date.now(),
      source: input.source ?? 'user',
    },
  };
}

/**
 * Validate a theme structure
 */
export function isValidTheme(theme: unknown): theme is Theme {
  if (typeof theme !== 'object' || theme === null) return false;

  const t = theme as Record<string, unknown>;
  if (typeof t.id !== 'string' || !t.id) return false;
  if (typeof t.name !== 'string' || !t.name) return false;
  if (typeof t.tokens !== 'object' || t.tokens === null) return false;

  const tokens = t.tokens as Record<string, unknown>;
  if (typeof tokens.colors !== 'object' || tokens.colors === null) return false;
  if (typeof tokens.typography !== 'object' || tokens.typography === null) return false;

  return true;
}
